### ISSUE TITLE
Trouble with implementation

### ISSUE THREAD

**Issue by cwoolum** [nbudin/devise_openid_authenticatable#20]
Hi,

I am trying to use this gem but am unsure of what to put in the controller. I am trying to integrate with Quickbooks and their identity url is 

https://openid.intuit.com/OpenId/Provider

Could you provide a quick example for authenticating?

**Comment by munkius** [comment]
@cwoolum If you still need it - after nearly 3 years - version 1.2.0 was just released providing a configurable identity_url.
